"""ficha de admision completa del paciente

Revision ID: baec577fc7e8
Revises: 3f8c1d9a2b47
Create Date: 2026-08-04 20:06:51.551438

"""
from collections.abc import Sequence

import sqlalchemy as sa
# SQLModel genera tipos propios (AutoString); sin este import las migraciones
# autogeneradas fallan con NameError.
import sqlmodel

from alembic import op

revision: str = 'baec577fc7e8'
down_revision: str | None = '3f8c1d9a2b47'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pacientes', sa.Column('documento', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True))
    op.add_column('pacientes', sa.Column('genero', sa.Enum('femenino', 'masculino', 'no_binario', 'desconocido', name='ck_pacientes_genero', native_enum=False, create_constraint=True), server_default='desconocido', nullable=False))
    op.add_column('pacientes', sa.Column('ocupacion', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True))
    op.add_column('pacientes', sa.Column('contacto_emergencia', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True))
    op.add_column('pacientes', sa.Column('telefono_emergencia', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.add_column('pacientes', sa.Column('obra_social', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True))
    op.add_column('pacientes', sa.Column('numero_afiliado', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=True))
    op.add_column('pacientes', sa.Column('derivado_por', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True))
    op.add_column('pacientes', sa.Column('fecha_inicio', sa.Date(), nullable=True))
    op.add_column('pacientes', sa.Column('modalidad', sa.Enum('presencial', 'virtual', 'mixta', name='ck_pacientes_modalidad', native_enum=False, create_constraint=True), server_default='presencial', nullable=False))
    op.add_column('pacientes', sa.Column('frecuencia', sa.Enum('semanal', 'quincenal', 'mensual', 'a_demanda', name='ck_pacientes_frecuencia', native_enum=False, create_constraint=True), server_default='semanal', nullable=False))
    op.add_column('pacientes', sa.Column('honorarios', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('pacientes', sa.Column('notas_administrativas', sa.Text(), nullable=True))
    op.create_unique_constraint('uq_paciente_terapeuta_documento', 'pacientes', ['terapeuta_id', 'documento'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_paciente_terapeuta_documento', 'pacientes', type_='unique')
    op.drop_column('pacientes', 'notas_administrativas')
    op.drop_column('pacientes', 'honorarios')
    op.drop_column('pacientes', 'frecuencia')
    op.drop_column('pacientes', 'modalidad')
    op.drop_column('pacientes', 'fecha_inicio')
    op.drop_column('pacientes', 'derivado_por')
    op.drop_column('pacientes', 'numero_afiliado')
    op.drop_column('pacientes', 'obra_social')
    op.drop_column('pacientes', 'telefono_emergencia')
    op.drop_column('pacientes', 'contacto_emergencia')
    op.drop_column('pacientes', 'ocupacion')
    op.drop_column('pacientes', 'genero')
    op.drop_column('pacientes', 'documento')
    # ### end Alembic commands ###
